apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  # K8s va encoder ça en base64 automatiquement au stockage
  DB_PASSWORD: "SuperSecret123"
  API_KEY: "cle-api-tres-secrete"